# Se puede arrancar el TP dsd este notebook que tiene el csv con una limpieza inicial

In [1]:
# importacion general de librerias y de visualizacion (matplotlib y seaborn)
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
entrenamiento = pd.read_csv('https://raw.githubusercontent.com/miguelAfonzalida/TP1-OrgaDatos/master/Entrenamieto_ECI_2020%20(1).csv?token=AG4D7WBO6A6NT3SMTQTQF3S7STKLG')
entrenamiento.head()

     Region   Territory  ...        Stage       Prod_Category_A
0      EMEA        None  ...  Closed Lost  Prod_Category_A_None
1      EMEA        None  ...   Closed Won  Prod_Category_A_None
2  Americas  NW America  ...   Closed Won  Prod_Category_A_None
3  Americas  NW America  ...  Closed Lost  Prod_Category_A_None
4  Americas  NW America  ...  Closed Lost  Prod_Category_A_None

[5 rows x 51 columns]